### ISSUE TITLE
SSL: UNKNOWN_PROTOCOL

### ISSUE THREAD

**Issue by gorivishal** [tenable/nessrest#115]
Getting SSL error even after using --insecure=True handle.

```
>>> ness6rest.Scanner(url="https://ohcinnessusscan:8834", login=os.environ['username'], password=os.environ['password'], insecure=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vgori/my-venv-py2.7/lib/python2.7/site-packages/nessrest/ness6rest.py", line 112, in __init__
    self._login(login, password)
  File "/Users/vgori/my-venv-py2.7/lib/python2.7/site-packages/nessrest/ness6rest.py", line 130, in _login
    retry=False)
  File "/Users/vgori/my-venv-py2.7/lib/python2.7/site-packages/nessrest/ness6rest.py", line 246, in action
    raise SSLException('%s for %s.' % (ssl_error, url))
nessrest.ness6rest.SSLException: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590) for https://ohcinnessusscan:8834/session.
>>> 
``` 

```
>>> ness6rest.Scanner(url="https://10.160.23.22:8834", login=os.environ['username'], password=os.environ['password'], insecure=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vgori/my-venv-py2.7/lib/python2.7/site-packages/nessrest/ness6rest.py", line 112, in __init__
    self._login(login, password)
  File "/Users/vgori/my-venv-py2.7/lib/python2.7/site-packages/nessrest/ness6rest.py", line 130, in _login
    retry=False)
  File "/Users/vgori/my-venv-py2.7/lib/python2.7/site-packages/nessrest/ness6rest.py", line 246, in action
    raise SSLException('%s for %s.' % (ssl_error, url))
nessrest.ness6rest.SSLException: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590) for https://10.160.23.22:8834/session
```

**Comment by mokuso** [comment]
My guess is that you are using an older version of OpenSSL, run "openssl version" to check. Support for TLS 1.1 and TLS 1.2 was added with OpenSSL 1.0.1

**Comment by gorivishal** [comment]
This is the certificate installed by default using Nessus scanner for MacOS. I even tried the Linux scanner on my Kali. Localhost openssl is at the latest level. Not sure how that's relevant though. 
```
root@kali:~/Downloads# openssl version
OpenSSL 1.1.0e  16 Feb 2017
```

**Comment by mokuso** [comment]
Its relevant as this is not a certificate error (--insecure handles that), it's a protocol error. If it was a certificate issue you would see the following:

```requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)```

Instead try the following within python interpreter:
```
>>> import ssl
>>> ssl.OPENSSL_VERSION
```

**Comment by gorivishal** [comment]
I was using python2.7.10. I changed my env to python2.7.13 which uses latest version of ssl which resolved the issue. Thanks.
